version: '3'

services:

  # container for node app
  path_app:
    build: ./
    env_file:
      - ./api_key.env
    environment:
      - PORT=8080
    links:
      - mongo
    ports:
      - "8080:8080"
    entrypoint: ["npm", "run", "$PATH_RUN:-start"]
    # uncomment to mount project folder in container
    # volumes: # change left part (path in your host machine) as needed
    #   - /home/my_user/src/path_app:/usr/src/path_app



  # container for mongodb
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes: # change left part (path in your host machine) as needed
      - ~/.mongo/db:/data/db
    # logging: # uncomment to stop db logging (e.g. for cleaner tests)
    #   driver: none
