version: '3'

services:

  # container for node app
  path_app:
    build: ./
    env_file:
      - ./api_key.env
    environment:
      - PORT=8080
      - DB_URL=mongodb://mongo/path_app
    links:
      - mongo
    ports:
      - "8080:8080"
    # uncomment the lines below to run path_app in dev mode
    # volumes: # change left part (path in your host machine) as needed
    #   - ~/src/path_app:/usr/src/path_app
    # entrypoint: ["npm", "run", "devstart"]


  # container for mongodb
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes: # change left part (path in your host machine) as needed
      - ~/.mongo/db:/data/db
